### ISSUE TITLE
Opening an empty channel crashes

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3537]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Symptoms:
  - crash

How to reproduce:
	1. Open new split dialog (Ctrl+T)
	2. Make sure that `Channel` is selected and nothing is typed in the box
	3. Press enter
	4. *crash*

```
13:37:55.931 default: unknown ASSERT: "uint(i) < uint(size())" in file /usr/include/qt/QtCore/qstring.h, line 1072
```

<details>
<summary>Backtrace</summary>

```
#0  0x00007f48f5ed9d22 in raise () at /usr/lib/libc.so.6
#1  0x00007f48f5ec3862 in abort () at /usr/lib/libc.so.6
#2  0x00007f48f681eee4 in qt_assert(char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#3  0x00007f48f681ef44 in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#4  0x000055fc4b89cb7c in QString::at(int) const (this=<optimized out>, this=0x7ffce29a5c50, i=0) at /usr/include/qt/QtCore/qstring.h:1072
#5  operator() (message=..., __closure=<optimized out>) at /home/mm2pl/chatterino2_main_repo/src/providers/irc/AbstractIrcServer.cpp:36
#6  std::__invoke_impl<void, chatterino::AbstractIrcServer::AbstractIrcServer()::<lambda(QString)>&, QString> (__f=<optimized out>) at /usr/include/c++/11.1.0/bits/invoke.h:61
#7  std::__invoke_r<void, chatterino::AbstractIrcServer::AbstractIrcServer()::<lambda(QString)>&, QString> (__fn=<optimized out>) at /usr/include/c++/11.1.0/bits/invoke.h:111
#8  std::_Function_handler<void(QString), chatterino::AbstractIrcServer::AbstractIrcServer()::<lambda(QString)> >::_M_invoke(const std::_Any_data &, QString &&) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/11.1.0/bits/std_function.h:291
#9  0x000055fc4bb88247 in std::function<void (QString)>::operator()(QString) const (__args#0=..., this=0x55fc4df15a08) at /usr/include/c++/11.1.0/bits/std_function.h:560
#10 chatterino::RatelimitBucket::handleOne() (this=0x55fc4df159f0) at /home/mm2pl/chatterino2_main_repo/src/util/RatelimitBucket.cpp:37
#11 0x000055fc4ba3bcef in chatterino::AbstractIrcServer::getOrAddChannel(QString const&) (this=this@entry=0x55fc4dc6e120, dirtyChannelName=...) at /home/mm2pl/chatterino2_main_repo/src/providers/irc/AbstractIrcServer.cpp:257
#12 0x000055fc4bbcf1d2 in chatterino::SelectChannelDialog::getSelectedChannel() const (this=0x55fc7ba07f60) at /home/mm2pl/chatterino2_main_repo/src/widgets/dialogs/SelectChannelDialog.cpp:353
#13 0x000055fc4bc6f619 in operator() (__closure=0x55fc78587d80) at /home/mm2pl/chatterino2_main_repo/src/widgets/splits/Split.cpp:730
#14 std::__invoke_impl<void, chatterino::Split::showChangeChannelPopup(char const*, bool, std::function<void(bool)>)::<lambda()>&> (__f=...) at /usr/include/c++/11.1.0/bits/invoke.h:61
#15 std::__invoke_r<void, chatterino::Split::showChangeChannelPopup(char const*, bool, std::function<void(bool)>)::<lambda()>&> (__fn=...) at /usr/include/c++/11.1.0/bits/invoke.h:111
#16 std::_Function_handler<void(), chatterino::Split::showChangeChannelPopup(char const*, bool, std::function<void(bool)>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=<optimized out>) at /usr/include/c++/11.1.0/bits/std_function.h:291
#17 0x000055fc4bbd0015 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/11.1.0/bits/std_function.h:560
#18 pajlada::Signals::Signal<>::invoke() (this=<optimized out>) at /home/mm2pl/chatterino2_main_repo/lib/signals/include/pajlada/signals/signal.hpp:41
#19 chatterino::SelectChannelDialog::closeEvent(QCloseEvent*) (this=<optimized out>) at /home/mm2pl/chatterino2_main_repo/src/widgets/dialogs/SelectChannelDialog.cpp:489
#20 0x00007f48f763167d in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#21 0x00007f48f75fb1a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#22 0x00007f48f6a0a9ba in QEvent::~QEvent() () at /usr/lib/libQt5Core.so.5
```

</details>

### Screenshots

N/A

### OS and Chatterino Version

Chatterino + Dankerino patches 3ce4a330505c9f0347e4caca9923b7b482ebff21 8e7fe991 Compiled with -O3

**Comment by Mm2PL** [comment]
this is my fault lol
