### ISSUE TITLE
[IRC] Sending message in non-established IRC connection crashes Chatterino

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#3570]
```
(gdb) bt
#0  0x0000557ff14e232a in chatterino::IrcServer::nick() (this=0x0) at /home/pajlada/git/chatterino/chatterino2/src/providers/irc/IrcServer.cpp:58
#1  0x0000557ff14d5447 in chatterino::IrcChannel::sendMessage(QString const&) (this=0x557ff36cb9d0, message=...)
    at /home/pajlada/git/chatterino/chatterino2/src/providers/irc/IrcChannel2.cpp:41
#2  0x0000557ff18a15e3 in operator()(std::vector<QString, std::allocator<QString> >) const (__closure=0x557ff3641b30, arguments=std::vector of length 0, capacity 0)
    at /home/pajlada/git/chatterino/chatterino2/src/widgets/splits/SplitInput.cpp:306
#3  0x0000557ff18a9212 in std::__invoke_impl<QString, chatterino::SplitInput::addShortcuts()::<lambda(std::vector<QString>)>&, std::vector<QString, std::allocator<QString> > >(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/11.1.0/bits/invoke.h:61
#4  0x0000557ff18a75cb in std::__invoke_r<QString, chatterino::SplitInput::addShortcuts()::<lambda(std::vector<QString>)>&, std::vector<QString, std::allocator<QString> > >(struct {...} &)
    (__fn=...) at /usr/include/c++/11.1.0/bits/invoke.h:116
#5  0x0000557ff18a5bf4 in std::_Function_handler<QString(std::vector<QString, std::allocator<QString> >), chatterino::SplitInput::addShortcuts()::<lambda(std::vector<QString, std::allocator<QString> >)> >::_M_invoke(const std::_Any_data &, std::vector<QString, std::allocator<QString> > &&) (__functor=..., __args#0=...) at /usr/include/c++/11.1.0/bits/std_function.h:292
#6  0x0000557ff141d64a in std::function<QString (std::vector<QString, std::allocator<QString> >)>::operator()(std::vector<QString, std::allocator<QString> >) const
    (this=0x557ff3641b30, __args#0=std::vector of length 0, capacity 0) at /usr/include/c++/11.1.0/bits/std_function.h:560
#7  0x0000557ff141350f in operator()() const (__closure=0x557ff3641b30) at /home/pajlada/git/chatterino/chatterino2/src/controllers/hotkeys/HotkeyController.cpp:73
```

**Comment by Mm2PL** [comment]
IRC support was removed

###### F
